### ISSUE TITLE
GitHub thinks this is SQLPL, not JavaScript

### ISSUE THREAD

**Issue by ThePrez** [markdirish/loopback-connector-ibmi#4]
The most trivial and unimportant of issues

 https://github.com/github/linguist#troubleshooting

**Comment by markdirish** [comment]
Commit 401ec6d902b7aae9e5fbf672675533b18e495253 :
Created a .gitattributes file to ignore `*.sql` files. There was only 1 (I think), but linguist weighs language based on file size, not count.
